# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       sfos-bepo

# >> macros
# << macros

Summary:    Bépo layout for sailfish OS
Version:    0.1
Release:    1
Group:      System/Packages
License:    LICENSE
URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  sfos-bepo.yaml
BuildRequires:  cmake

%description
Short description of my Sailfish OS Application


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake . 
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
/usr/share/maliit/plugins/com/jolla/layouts/layouts_bepo.conf
/usr/share/maliit/plugins/com/jolla/layouts/fr_bepo.qml
# >> files
# << files
